using System;
using System.Web;

namespace Com.Gosol.KNTC.Security
{
    public enum ChucNangEnum
    {
        HeThong = 1,
        ThongTinCaNhan = 2,
        QuanLyNguoiDung = 3,
        QuanLyNhomNguoiDung = 5,
        QuanLyPhanQuyen = 6,
        QuanLyCanBo = 7,
        ThamSoHeThong = 9,
        SaoLuuDuLieu = 68,
        NhatKyHeThong = 69,
        DongBoDuLieu = 190,
        XoaDonThuLoi = 195,
        QLEmail = 212,
        QuyTrinhHeThong = 214,
        HuongDanSuDung = 215,
        ThongKeNhapLieu = 600,
        CauHinhQuyTrinh = 603,

        DanhMuc = 20,
        DanhMucNgheNghiep = 21,
        DanhMucDanToc = 22,
        DanhMucQuocTich = 23,
        DanhMucTinhHuyenXa = 24,
        DanhMucLoaiDoiTuongKN = 25,
        DanhMucLoaiDoiTuongBiKN = 26,
        DanhMucCoQuan = 27,
        DanhMucThamQuyen = 28,
        DanhMucChucVu = 29,
        DanhMucNguonDonDen = 30,
        DanhMucLoaiKhieuTo = 31,
        DanhMucHuongGiaiQuyet = 32,
        DanhMucTrangThaiDon = 33,
        DanhMucLoaiKetQua = 34,
        DanhMucPhanTichKQ = 35,
        DanhMucLoaiVB = 36,
        DanhMucFileDinhKem = 37,
        QuanLyChiaTachSapNhapCoQuan = 211,
        DanhMucBieuMau = 213,

        TiepCongDan = 300,
        TiepDanThuongXuyen = 301,
        TiepDanDinhKy = 302,
        TiepDanDotXuat = 303,
        TiepNhanDon = 306,
        SoTiepDan = 307,

        XuLyDon = 310,
        PhanXuLyDon = 311,
        XuLyDonThu = 312,
        PheDuyetKetQuaXuLy = 313,
        CapNhatVanBanGiaoXacMinh = 314,
        PhanXuLyDonChuTich = 315,
        DSDonThuCanDonDoc = 316,
        QuanLyHoSoDonThu = 317,

        GiaiQuyetDon = 320,
        PhanGiaiQuyetDon = 321,
        XacMinhNoiDungDon = 322,
        PheDuyetKetQua = 323,
        GiaiQuyetDonThu = 324,
        CapNhatQuyetDinhGiaiQuyet = 325,
        CapNhatToXacMinh = 326,
        QuanLyVuViecPhucTap = 329,
        NhapKetQuaTranhChap = 602,

        ThucHienQuyetDinhKetLuan = 330,
        CapNhatVBGiaiQuyet = 331,
        ThiHanh = 332,

        TraCuu = 400,
        LichTiepDan = 401,
        TrinhTuThuTuc = 402,
        TraCuuQuyetDinhGiaiQuyet = 403,
        TraCuuTrangThaiHoSo = 404,

        KeKhaiDuLieuDauKy = 500,
        KeKhaiDuLieuDauKyTCD01 = 501,
        KeKhaiDuLieuDauKyTCD02 = 502,
        KeKhaiDuLieuDauKyXLD01 = 503,
        KeKhaiDuLieuDauKyXLD02 = 504,
        KeKhaiDuLieuDauKyXLD03 = 505,
        KeKhaiDuLieuDauKyXLD04 = 506,
        KeKhaiDuLieuDauKyKQGQ01 = 507,
        KeKhaiDuLieuDauKyKQGQ02 = 508,
        KeKhaiDuLieuDauKyKQGQ03 = 509,
        KeKhaiDuLieuDauKyKQGQ04 = 510,

        BaoCao = 222,
        TCD01  = 223,
        TCD02  = 224,
        XLD01  = 225,
        XLD02  = 226,
        XLD03  = 227,
        XLD04  = 228,
        KQGQ01 = 229,
        KQGQ02 = 230,
        KQGQ03 = 231,
        KQGQ04 = 232,

        BCKienNghiPhanAnh = 700,
        BCLoaiKhieuTo = 701,
        BCCoQuanChuyenDon = 702,
        BCDiaChiChuDon = 703,
        BCTheoNoiPhatSinh = 704,
        BCVuViecDongNguoi = 705,
        BCRutDon = 706,
        BCTinhHinhTiepDan = 707,
        BCXuLyCongViec = 708,


        DashBoard = 800,
		DashBoardTong = 801,

    }

};